name: GCP deploy

on:
  release:
    types:
      - created
      
env:
  PROG_ID: ${{ secrets.PROG_ID }}
  APPLICATION_FILE: src/main/resources/application.properties

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: app-prop
      env:
        APP_PROP: ${{ secrets.APP_PROP }}
      run: |
        echo "$APP_PROP" | base64 -d > "$APPLICATION_FILE"
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache maven modules
      uses: actions/cache@v2
      env:
        cache-name: cache-mvn-modules
      with:
        path: ~/.m2
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Login to GCR
      uses: docker/login-action@v1
      with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
    - name: build
      run: |
        docker build -f src/main/docker/Dockerfile.multistage -t gcr.io/"$PROG_ID"/shorter-url:"$RELEASE_VERSION" .
    - name: push
      run: |
        docker push gcr.io/"$PROG_ID"/shorter-url:"$RELEASE_VERSION"

